name: vuepress

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: vuepress build
      run: |
        npm install -g vuepress
        vuepress build
    - name: commit docs
      run: |
        git config --global user.name "ryscheng-bot"
        git config --global user.email "ryscheng-bot@oasislabs.com"
        git add docs/
        git commit -m "Build docs"
