name: vuepress
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx vuepress build
    - name: commit docs
      run: |
        git config --global user.name "nhynes"
        git config --global user.email "nhynes@oasislabs.com"
        cd .vuepress/dist
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oasislabs/docs.git
        git add .
        git commit -m "Update docs"
        git push origin HEAD:gh-pages -f
