name: vuepress
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx prettier --write --trailing-comma=all --single-quote src/.vuepress/config.js
    - name: build docs
      run: |
        git config --global user.name "nhynes"
        git config --global user.email "nhynes@oasislabs.com"
        cd src
        npx vuepress build
        cd .vuepress
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oasislabs/docs.git --branch gh-pages --depth 1
        rm -rf docs/*
        mv dist/* docs
        cd docs
        git add -A
        git commit -m "Update docs"
        git push
